### PR TITLE
Add missing library dependencies

### PR DESCRIPTION
**Pull request by knoepfel**
Also include change to ROOT target-based dependencies.

This is part of a coordinated set of PRs that accomplish two tasks:

- Switching to geometry collections that own by value instead of by pointer
- Switching the (AuxDet) geometry systems to be thread-safe within a run

There are breaking changes associated with this PR, and they will be presented at the next LArSoft coordination meeting.

### CODE REVIEW

**Comment by gartung** [comment]
code-checks

**Comment by gartung** [comment]
trigger build

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
trigger build using branchname feature/knoepfel_threadsafe_geometry

**Comment by gartung** [comment]
trigger build using branchname feature/knoepfel_threadsafe_geometry in repos larcore, larcorealg, larreco, larsim, larevt

**Comment by knoepfel** [comment]
approve

**Pull request merged**
