### PR TITLE
"larreco

### PR DESCRIPTION
**Pull request by lgarren**

### CODE REVIEW

**Comment by lgarren** [comment]
code-checks

On 11/21/19 12:35 PM, Fermilab build bot account wrote:

A new Pull Request was created by @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=poY0Ew4waMNwecBRKIRbv7-a_bdrs1il_vhTCGKgNYE&e=> (Lynn Garren) for develop.

It involves the following packages:

larreco

@tomjunk<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tomjunk&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=p-HTNyFXmMFbjnagNbUJBkMqMF6FVtM5q9uQAx4UG1w&e=>, @knoepfel<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knoepfel&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=Djcu63elSlwinoniOfflVUZiAdgaAMe_mnxpdfYt5kA&e=>, @lgarren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lgarren&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=poY0Ew4waMNwecBRKIRbv7-a_bdrs1il_vhTCGKgNYE&e=>, @gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=yDLhycdQXdLAz1HU9KUE5jkTchT6hKs_7uG03B472xU&e=>, @FNALbuild<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_FNALbuild&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=lnJ9fNntx26HT2vhLZJgNvayi7fLWkrphr4VPITzJsk&e=>, @dladams<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dladams&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=L-GRw7o5sNlcDtXBjNv-_-rSEZPk7ehXskDhj0FxATU&e=>, @erica-snider<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_erica-2Dsnider&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=GJXuoyfx6Pm0hr6yQv96fIgmoaNsjPPRWxp1Ylhf9iM&e=>, @yangtj207<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yangtj207&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=s9zoQ4uI9DliSkPouGgT7YwOtLY1KxNp9F-rAMN38WY&e=>, @SFBayLaser<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SFBayLaser&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=BBNM6ex3QBh3WIQYVA7Q_gWjoEJn1kox9dnbb9nZynQ&e=>, @chalt007<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chalt007&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=phLYs6w4PraI7vWAlQ012cyWITLZfSH7NUttFcKzx2Q&e=>, @vitodb<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vitodb&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=GUtqc1H3dDMz5M7qvLqgsmXBjTdxkjS6OIE47kfaU8s&e=>, @chissg<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chissg&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=kl2NZBFQI98fKzX6dwe15kI0DfPLZPkbMbnithJ5-h0&e=>, @hgreenlee<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hgreenlee&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=cKMjWbPJL19gA0wcAh7VHq-1JAcdoPBfA0C7FoTlax4&e=> can you please review it and eventually sign? Thanks.
@gartung<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gartung&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=yDLhycdQXdLAz1HU9KUE5jkTchT6hKs_7uG03B472xU&e=> this is something you requested to watch as well.

cms-bot commands are listed here<https://urldefense.proofpoint.com/v2/url?u=http-3A__cms-2Dsw.github.io_cms-2Dbot-2Dcmssw-2Dcmds.html&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=sNjVlFG8hsfzZNAV01Xy74knrjPyy624RlUoM0AeoyE&s=rLpYww3V2jbo-FCxxdtE7DVnPKpQccp6yxUr9jFxrok&e=>

**Comment by gartung** [comment]
The trigger for the code check was never made because the script failed running on a node without py-github. Re-running the jenkins job did not trigger the job either because of the comment "The code-checks are being triggered in jenkins." from FNALbuild. Only running the jenkins code-check job by hand worked and the results were finally reported.

**Comment by lgarren** [comment]
Thanks for that explanation.  I am still a bit confused.  One email I got said only FNALbuild could approve.  Was that somehow related to where the job ran?

Lynn


On 11/22/19 10:01 AM, Patrick Gartung wrote:

The trigger for the code check was never made because the script failed running on a node without py-github. Re-running the jenkins job did not trigger the job either because of the comment "The code-checks are being triggered in jenkins." from FNALbuild. Only running the jenkins code-check job by hand worked and the results were finally reported.

**Comment by gartung** [comment]
The email address for the FNALbuild account is the listserv list. If you clicked on the link from an email sent to the listserv list it would only work if you were logged into the FNALbuild account. I got an error message when I clicked on a link in an email sent to the listserv list too.

**Comment by gartung** [comment]
+ups

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
merge

**Pull request merged**
