### PR TITLE
Additional 3D reconstruction improvements

### PR DESCRIPTION
**Pull request by brballer**

### CODE REVIEW

**Comment by absolution1** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The CI tests are normal.

**Comment by absolution1** [comment]
approve

**Comment by aihimmel** [comment]
@brballer -- Can you say a few words about what the intended changes are here, and who they are expected to affect? I'm afraid I can't parse that out from looking at the commits.

**Comment by brballer** [comment]
Alexander,

The issue is how to reconstruct multiple 2D trajectories (that have a very small variation in X) in 3D. The latest TrajCluster release fixed the major problems but didn’t incorporate the most recent changes that have been made.

Bruce

**Comment by lgarren** [comment]
approve

**Pull request merged**
