### PR TITLE
put in a check on the iterator for the hit sum accumulation -- end cannot be before begin

### PR DESCRIPTION
**Pull request by tomjunk**
In the SBND CI test 

lar -c sbnd_ci_nucosmics_reco1_quick_test_sbndcode.fcl nucosmics_detsim_test_sbndcode_Reference.root

there is a segmentation fault on this line in GausHitFinder_module.cc

                double HitsumADC = std::accumulate(HitsumStartItr, HitsumEndItr, 0.);

Some investigation revealed that in this case, numHits == nGausForFit (==3 in the case of the segfault). While HitsumStartItr and HitsumEndItr start out with the end > start, there is an if condition depending on numHits and nGausForFit that's different for the part that modifies HitsumStartItr and the part that modifies HitsumEndItr.  If in the case numHits == nGausForFit, it happend that the first if clause executed but the second did not, and the variable newright was left at its initialized value, 9999.  To the test on newright vs newleft succeeded, although HitsumEndItr < HitSumStartItr, and the std::accumulate segfaulted.

This PR puts in a bulletproofing check that looks like the one already in there.  It would be good to get feedback from the authors of the algorithm if this is intended behavior, whether skipping around these is the right thing to do, or something would be systematically wrong with the last hits in a group of hits.

### CODE REVIEW

**Comment by tomjunk** [comment]
This PR was started from larreco v09_26_00.  Surprisingly, GitHub says it can be merged into develop.  Maybe Git is smart enough to be able to add my one line in the right place.  SBND may need a v9.x fix, but ask Bear Carlson about that.

**Comment by tomjunk** [comment]
I put Kyle in as a reviewer, but Anselmo Meregaglia wrote the lines in question.

**Comment by tomjunk** [comment]
Bear tells me he would like this bugfix ported to v9_92_xx.

**Comment by absolution1** [comment]
I reached out to @amerega .  Anselmo confirmed that the fix looks good.

**Comment by gartung** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

There was weirdness with the previous attempt.

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
+1

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
