### PR TITLE
New Calorimetry Module

### PR DESCRIPTION
**Pull request by gputnam**
This pull request incorporates two new modules into larreco. It builds off Ed's two pull requests in larreco and lardataalg. Those would need to be merged before this one would successfully merge/build.

The first module (and the primary thrust of this pull request) is the GnocchiCalorimetry module. This code is intended for use to calculate the calorimetry of recob::Track objects. It is largely a rewrite of the existing Calorimetry module, with code cleaned up for easier extensibility. In the default configuration of the module, it will produce identical output to the Calorimetry module (two exceptions: DeadWireResRange's are not computed, and the PlaneID is always valid in Gnocchi whereas sometimes the original model will output invalid plane ID's). This has been verified to floating point precision. 

In addition to this default configuration, the new module offers a few new features that are motivated by developments in SBN. First: it enables the track pitch calculation required by the space charge correction methodology described in Ed's pull requests. Second, it enables correcting for E-field distortions directly in the calorimetry code. Third, it enables the use of the recob::Hit SummedADC() method to compute the charge of a hit, in addition to the existing Amplitude() and Integral() methods. The charge computation underlied by SummedADC() organizes individual hits into groups called "Snippets" and some of the code in the new module accommodates this organization. 

The second module is the CaloCheck module. It verifies that two individual anab::Calorimetry objects are identical. This is the module that was used to verify the GnocchiCalorimetry output.

### CODE REVIEW

**Comment by lgarren** [comment]
@gputnam @etyley  Will this work also be presented by Ed tomorrow?

**Comment by etyley** [comment]
Yes, I this will be covered in the presentation tomorrow

**Comment by lgarren** [comment]
unit test are now fine

**Comment by lgarren** [comment]
approve

**Pull request merged**
