### PR TITLE
Fixed MagneticField service for nug4 v1_07_00

### PR DESCRIPTION
**Pull request by ebrianne**
Fix MagneticField service in TrackFinder due to modifications of the MagneticField service in the nug4 package (v1_07_00)
See issue: https://cdcvs.fnal.gov/redmine/issues/25534

### CODE REVIEW

**Comment by lgarren** [comment]
Note that this PR also requires LArSoft/larsim#65 and  LArSoft/larg4#22

**Comment by lgarren** [comment]
To trigger the CI tests:
`trigger --build-delay 0 --cert /tmp/x509up_u1147 --version develop  --workflow default_wf --revisions "LArSoft/larg4#22 LArSoft/larsim#65 LArSoft/larreco#28"`

**Comment by lgarren** [comment]
@ebrianne the gensingle unit test has failed.  This test is in larsim.  I've given you access to edit LArSoft/larsim#65 on my fork.  
https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/10822&builds=

**Comment by lgarren** [comment]
Triggering the build again with lardata PR.
`trigger --build-delay 0 --cert /tmp/x509up_u1147 --version develop  --workflow default_wf --revisions "LArSoft/larg4#22 LArSoft/larsim#65 LArSoft/larreco#28 LArSoft/lardata#14"`

**Comment by lgarren** [comment]
CI results:
https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/10829&builds=
https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/1669&builds=
  unrelated version conflict
https://dbweb0.fnal.gov/LarCI/app/ns:uBooNE/view_builds/index?offset=0&builds=uboone_ci/5980&builds=
  nug4 version conflict
https://dbweb0.fnal.gov/LarCI/app/ns:ArgoNeuT/view_builds/index?offset=0&builds=argoneut_ci/5546&builds=
  OK
https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/6126&builds=
  OK
https://dbweb0.fnal.gov/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/10997&builds=
  warnings, probably normal

**Comment by lgarren** [comment]
Added a branch for testing and triggered the build again.
`trigger --build-delay 0 --cert /tmp/x509up_u1147 --version develop  --workflow default_wf --revisions "LArSoft/larg4#22 LArSoft/larsim#65 LArSoft/larreco#28 LArSoft/lardata#14 ubcore@feature/lg_test_nug4_v1_07_00"`

**Comment by lgarren** [comment]
CI tests again
https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/10834&builds=
https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/1671&builds=
https://dbweb0.fnal.gov/LarCI/app/ns:ArgoNeuT/view_builds/index?offset=0&builds=argoneut_ci/5548&builds=
https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/6133&builds=
https://dbweb0.fnal.gov/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/11002&builds=
https://dbweb0.fnal.gov/LarCI/app/ns:uBooNE/view_builds/index?offset=0&builds=uboone_ci/5982&builds=

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
