### PR TITLE
Update to Gnocchi Calorimetry Module for Use in ICARUS

### PR DESCRIPTION
**Pull request by gputnam**
Updated to correctly use the Space-Charge service in ICARUS. Also some tweaks for refactoring.

I have verified that the updated module does not change the output data at all except for the bugfixes.

### CODE REVIEW

**Comment by gputnam** [comment]
Is there a procedure for getting this PR approved? I had asked @PetrilloAtWork to take a look -- could he be the reviewer?

**Comment by lgarren** [comment]
@gputnam  We are aware of this PR and it is in the que for the approval process.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The argonuetcode CI results are good: https://dbweb8.fnal.gov:8443/LarCI/app/ns:ArgoNeuT/view_builds/index?offset=0&builds=argoneut_ci/5872&builds=

**Comment by SFBayLaser** [comment]
approve

**Pull request merged**
