### PR TITLE
Feature/etyley sce v9

### PR DESCRIPTION
**Pull request by etyley**
- Changes to CalorimetryAlg to allow for passing of a local electric field when converting dQdx -> dEdx. Requires lardataalg [PR 12](https://github.com/LArSoft/lardataalg/pull/12). 
- Added SCECorrection module which takes in the output of pattern recognition (Pandora) and corrects the positions of all 3D objects in a slice. This uses the space charge service under the hood, and is simply meant to bring the corrections to the earliest possible stage in the reconstruction process so that downstream algorithms (i.e. track shower and calorimetry object building) will have spatially corrected inputs.

### CODE REVIEW

**Comment by lgarren** [comment]
See https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/9546&builds=

**Comment by lgarren** [comment]
See this set of CI tests.  It looks like there is a problem with dunetpc.  argoneutcode, sbnd, and icarus seem OK.
https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/9543&builds=

**Comment by lgarren** [comment]
Direct link to the dunetpc CI https://dbweb0.fnal.gov/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/10253&builds=

**Comment by etyley** [comment]
I did not realise dunetpc had it's own version of the detector propery service that also needed changing. I have done that now on [feature/etyley_sce_v9](https://cdcvs.fnal.gov/redmine/projects/dunetpc/repository?utf8=%E2%9C%93&rev=feature%2Fetyley_sce_v9) which I have complied locally, although I assume you will trigger the CI again?

**Comment by lgarren** [comment]
Thank you.  I have manually triggered the CI again.

**Comment by lgarren** [comment]
CI tests are now normal
https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/9563&builds=
https://dbweb5.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/9562&builds=

**Comment by lgarren** [comment]
approve

**Pull request merged**
