### PR TITLE
use rstartree ups product

### PR DESCRIPTION
**Pull request by lgarren**

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
Ooops - triggered the build before rstartree v2016_07 was available.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The dune CI was run with this PR and dunereco PR 13.   There are CI failures.  Need to find out if they are related to this change.
https://dbweb8.fnal.gov:8443/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/13192&builds=

**Comment by lgarren** [comment]
DUNE fixed some unrelated problems.  The DUNE CI test is now normal:
https://dbweb8.fnal.gov:8443/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/13201&builds=

**Comment by lgarren** [comment]
@LArSoft/level-2-managers  Please take a look at this PR and approve or comment.  

Note that larreco/ClusterFinder/RStarTree is a copy of third party software, which is available at https://github.com/virtuald/r-star-tree.  In order to avoid licensing conflicts, we plan to remove larreco/ClusterFinder/RStarTree in favor of a rstartree ups product.

**Comment by absolution1** [comment]
approve

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
