### PR TITLE
Third cosmetic change to test GitHub PR process

### PR DESCRIPTION
**Pull request by erica-snider**

### CODE REVIEW

**Comment by erica-snider** [comment]
trigger build

**Comment by gartung** [comment]
When run from the command line the process_pr.py script correctly changes the labels to tests-approved. When run in the jenkins job it does not. Still trying to debug why. 
@knoepfel can you please comment with your L2 approval.

**Comment by lgarren** [comment]
I've been trying to figure out how we see the output of the CI tests.  All I see on the appropriate web report is a column that the tests have been successfully triggered.  Do we know where to see final results?

On 1/13/20 4:37 PM, Patrick Gartung wrote:

When run from the command line the process_pr.py script correctly changes the labels to tests-approved. When run in the jenkins job it does not. Still trying to debug why.
@knoepfel<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_knoepfel&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=P0Z7nIv69Nz5OP_L9NyELQ&m=I8AP0cJO_S9iSw_gGW8IctOvzZkNba6F0F48Nzi7oxc&s=y7lb0Pi0Y9WMkvYCS4BJeB-3JuovBFSSEYOH2BSsJTs&e=> can you please comment with your L2 approval.

**Comment by erica-snider** [comment]
So the current state is that tests have run, but the PR has not been updated with that status?

**Comment by gartung** [comment]
Yes. If I run the same command that the jenkins job runs at the command prompt then the status is updated as expected. There might be some weirdness with the way the java virtual machine handles line breaks. I am investigating.

**Comment by knoepfel** [comment]
approve

**Comment by gartung** [comment]
approved

**Comment by gartung** [comment]
merge

**Pull request merged**
