### PR TITLE
Implemented TensorRT inference server client interface in PointIdAlg

### PR DESCRIPTION
**Pull request by mhlswang**

### CODE REVIEW

**Comment by gartung** [comment]
code-checks

**Comment by gartung** [comment]
trigger build

**Comment by lgarren** [comment]
@knoepfel  please review

**Comment by lgarren** [comment]
I do not think that this code will build.  There does not appear to be a corresponding change in ups/product_deps to add a dependency on trtis_clients.  Also, this code MUST be optional and modular.  trtis_clients is ONLY available for SLF7 e19 builds.  It is not available for other platforms or for clang.

@erica-snider  Do you have comments about this?   We have two models at this point: tensorflow integrated as an optional part of larreco and the newer larwirecell, which is a separate repository.

**Comment by lgarren** [comment]
This PR has been merged manually and is part of the new larrecodnn repository.

**Pull request closed without merging**
