### PR TITLE
Use the WireReadoutGeom::Plane() method accepting a TPCID and a view instead of PlaneID to make PDDP happy

### PR DESCRIPTION
**Pull request by tomjunk**
In the V10 refactored geometry, there has been a pattern of finding the wire pitch by querying the WireReadoutGeometry to get a Plane from a PlaneID, and then querying that to get WirePitch.  The issue is that forming the arguments to WireReadoutGeometry::Plane() by using a view instead of a plane number breaks when running ProtoDUNE-DP reconstruction.  The views in PD-DP are numbered 2 and 3, but the planes have different numbers, and these lines throw exceptions.  Fortunately there is a second way of getting a Plane out of WireReadoutGeometry once the view is known, and for the most part, it just involves moving a right-brace over.  There are two instances here, and some in larpandora.

### CODE REVIEW

**Comment by tomjunk** [comment]
Formatted code -- a line got shortened and the code formatter wanted to collapse it back down from two lines in the original to just one.

**Comment by knoepfel** [comment]
trigger build

**Comment by tomjunk** [comment]
DUNE tests need dunecore PR 118 to succeed.  And larpandora PR 41

**Comment by lgarren** [comment]
trigger build with pull requests #73, LArSoft/larpandora#41, DUNE/dunecore#118

**Comment by lgarren** [comment]
approve

**Review by absolution1 — APPROVED** [review]
Looks good to me.  Thank you @tomjunk

**Comment by absolution1** [comment]
approve

**Pull request merged**
