### PR TITLE
Angular Dependent Recombination Correction

### PR DESCRIPTION
**Pull request by gputnam**
Allow to configure recombination parameters. Allow for angular dependence in parameters coupled to E-field.

These updates are intended to be backwards compatible. Anyone using the relevant module will not need to update their configuration.

### CODE REVIEW

**Comment by knoepfel** [comment]
Thanks for the PR, @gputnam.  Can you run the code-formatter as described above at https://github.com/LArSoft/larreco/pull/59#issuecomment-1656326301?

**Comment by knoepfel** [comment]
Thanks for the PR, @gputnam.  Can you run the code-formatter as described above at https://github.com/LArSoft/larreco/pull/59#issuecomment-1656326301?

**Comment by gputnam** [comment]
@knoepfel just did! The latest commit has the fixed formatting.

**Comment by knoepfel** [comment]
Thanks @gputnam.  The changes look sensible to me.  Let's see what the CI says.

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@LArSoft/level-2-managers please review and approve or comment

**Comment by tomjunk** [comment]
Approved

I'll approve this as it seems like it provides an extra handle on improving reco and it defaults to the old behavior.

This all looks good and it looks backwards compatible. The default mod box B function is [0] which is filled in from util::kModBoxB, and it doesn't depend on phi.  The question I have is that the DetectorPropertiesStandard service has a non-angular dependent modified box correction formula

https://github.com/LArSoft/lardataalg/blob/7b3f787c56963cafa0d37140788b7b3ea47fdda7/lardataalg/DetectorInfo/DetectorPropertiesStandard.cxx#L323

A quick search through the source code in larsoft doesn't show anyone calling that detector properties service.  There's a commented-out call in larpandora/LArPandoraAnalysis/PFParticleTrackingAna_module.cc

larsim/IonizationScintillation/ISCalcSeparate.cxx

also has a non-angular-dependent modified box formula in it.

**Comment by lgarren** [comment]
approve

**Pull request merged**
