### PR TITLE
Move MarqFitAlg to larvecutils

### PR DESCRIPTION
**Pull request by cerati**
This PR updates the larreco package after migration of MarqFitAlg to the newly created larvecutils package.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build with pull requests #37, LArSoft/lardata#21

**Comment by lgarren** [comment]
Note that the uboone unit tests are fine in a local build with these PRs.

**Comment by absolution1** [comment]
approve

**Comment by lgarren** [comment]
approve

**Pull request merged**
