### PR TITLE
Solution for Redmine issue #23457.

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Testing the pull request system.

### CODE REVIEW

**Comment by lgarren** [comment]
trigger build

I am skipping the code-checks step.  That will happen during build anyway.

**Comment by vitodb** [comment]
CI dashboard for those LArSoft builds from GitHub are available in the test instance of the CI:
http://test-ci-history.fnal.gov/TestCI/app/view_builds/index

**Comment by lgarren** [comment]
@knoepfel  do you want to comment and/or approve?

**Comment by knoepfel** [comment]
approve

Looks good.

**Pull request merged**
