### PR TITLE
Modification to add ROISummedADC and HitSummedADC

### PR DESCRIPTION
**Pull request by amerega**
Commit related to the LArSoft meeting
https://indico.fnal.gov/event/64331/
This commit is related to 3 parallel requests in: larreco, lardata and lardataobj

!! For the experts please have a look at:
 line 117 of larreco/HitFinder/RFFHitFinderAlg.cxx 
lines 415-417 of larreco/HitFinder/RawHitFinder_module.cc 
lines 628 of larreco/RecoAlg/CCHitFinderAlg.cxx

### CODE REVIEW

**Comment by knoepfel** [comment]
code-checks

**Comment by lgarren** [comment]
code-checks

**Comment by amerega** [comment]
Dear all, is there anything blocking my pull request? If not when will it be treated? Thanks in advance

**Comment by lgarren** [comment]
approve

**Pull request merged**
